// Seeds are verified channel names from the public reference site directory, not verified stream URLs.
const groups = {
'فارسی': 'Pars TV|Iran International|BBC Persian|VOA PNN|Iran Wire|Mihan TV|Channel One|Manoto TV|Radio Farda TV|Euronews FA|Simaye Azadi|Iran Independent|PMC|PMC Royale|Navahang TV|Tapesh|Tapesh Iran|MBC Persia|4U TV|4U Family|T2 TV|T2 Movies|Persiana TV|Persiana Music|Persiana Cinema|Persiana Series|Persiana Doc|Persiana Science|Persiana Comedy|Persiana Sports 1|Persiana Sports 2|GEM TV|GEM Series|GEM Film|GEM Drama|GEM Comedy|GEM Kids|GEM Life|GEM Classic|GEM Bollywood|GEM Nature|GEM Food|GEM Junior|GEM Music|GEM Sport|Khatereh TV|Ekran Movies|Afra Film|Afra Series|Grand Cinema|Oxir TV|Royal Time TV',
'ایران': 'Shabake 1|Shabake 2|Shabake 3|Shabake 4|Shabake 5|Shabake Khabar|Shabake Khabar 2|Varzesh|Mostanad|Nasim|Namayesh|Tamasha|Pooya|Omid|Salamat|Amouzesh|iFilm Farsi|iFilm English|iFilm Arabic|iFilm Dari|Press TV|Ofogh|Quran|Alalam|IRNA TV',
'استانی': 'Abadan|Alborz|Ardabil|Birjand|Bojnourd|Booshehr|Chahar Mahal|Esfahan|Fars|Gilan|Golestan|Hamedan|Hormozgan|Ilam|Kerman|Kermanshah|Khoozestan|Kish|Kordestan|Lorestan|Mahabad|Markazi|Mashhad|Mazandaran|Qazvin|Qom|Semnan|Sistan|Tabriz|Urmia|Yasouj|Yazd|Zanjan',
'اخبار جهان': 'Sky News|CBS News|Bloomberg|ABC News|France 24 EN|Aljazeera|BBC News|WION|DW News|NHK World|TRT World|Euronews EN|Euronews FR|Euronews RU|Fox Weather|AccuWeather|CGTN English|CNA TV|Global News|Yahoo Finance|Newsmax TV|ABC News AU|France 24 FR',
'ترکیه': 'ATV|TRT 1|TRT 2|TRT Haber|TRT Muzik|TRT Cocuk|TRT Spor|TRT Spor 2|CNN Turk|Show TV|Star TV|Kanal 7|Kanal D|Halk TV|A Haber|A Spor|Bloomberg HT|Power Turk|Power TV|NTV Izle|Haberturk TV|TV100|TGRT Haber|Beyaz TV',
'ارمنستان': '1TV Armenia|1TV News|1TV America|AMGA TV|Song TV|USArmenia TV|TBN Armenia|Nor Hayastan|AABC TV|ARTN Shant TV',
'مستند': 'NASA TV|Travelxp|Go2Travel TV|GoTraveler|HD Travel TV|Law & Crime|Nat Geo|Nat Geo Wild|BBC Earth|CGTN Doc|True History|RT Documentary|Military History',
'رادیو': 'Radio Hamrah|Radio Yar|Radio Ran|Radio Setareh|Radio Shadi|Radio Navahang|Radio Farda Rd|Iran Intl Radio|Radio Parsa|Radio Mihan|Radio Novin|Radio Ava IR',
'بین‌المللی': 'ZDF|RTL|RTL 2|ProSieben|Sat1|NDR|Das Erste|WDR|DMAX|Arirang TV|CGTN Spanish|DW Spanish|France 24 ES|Telemundo|TV Azteca|Univision TV|Todo Noticias|RT Spanish|India TV News|Dawn News|9XM|Bollywood HD|Kan 11|Keshet 12|Reshet 13|Makan 33|JBS TV|Channel 24|UA TV'
};
// Display labels are separate from reference site's Latin channel identifiers.
const persianNames = {
'Pars TV':'پارس تی‌وی','Iran International':'ایران اینترنشنال','BBC Persian':'بی‌بی‌سی فارسی','VOA PNN':'صدای آمریکا','Iran Wire':'ایران وایر','Mihan TV':'میهن تی‌وی','Channel One':'کانال یک','Manoto TV':'من‌وتو','Radio Farda TV':'رادیو فردا','Euronews FA':'یورونیوز فارسی','Simaye Azadi':'سیمای آزادی','Iran Independent':'ایران ایندیپندنت','PMC':'پی‌ام‌سی','PMC Royale':'پی‌ام‌سی رویال','Navahang TV':'نواهنگ','Tapesh':'طپش','Tapesh Iran':'طپش ایران','MBC Persia':'ام‌بی‌سی پرشیا','4U TV':'فور یو','4U Family':'فور یو فمیلی','T2 TV':'تی‌تو','T2 Movies':'تی‌تو موویز','Persiana TV':'پرشیانا تی‌وی','Persiana Iranian':'پرشیانا ایرانی','Persiana Music':'پرشیانا موزیک','Persiana Cinema':'پرشیانا سینما','Persiana Series':'پرشیانا سریال','Persiana Doc':'پرشیانا مستند','Persiana Science':'پرشیانا علم','Persiana Comedy':'پرشیانا کمدی','Persiana Sports 1':'پرشیانا اسپرت ۱','Persiana Sports 2':'پرشیانا اسپرت ۲','GEM TV':'جم تی‌وی','GEM Series':'جم سریال','GEM Film':'جم فیلم','GEM Drama':'جم دراما','GEM Comedy':'جم کمدی','GEM Kids':'جم کودک','GEM Life':'جم لایف','GEM Classic':'جم کلاسیک','GEM Bollywood':'جم بالیوود','GEM Nature':'جم طبیعت','GEM Food':'جم غذا','GEM Junior':'جم جونیور','GEM Music':'جم موزیک','GEM Sport':'جم اسپرت','Khatereh TV':'خاطره','Ekran Movies':'اکران فیلم','Afra Film':'افرا فیلم','Afra Series':'افرا سریال','Grand Cinema':'گرند سینما','Oxir TV':'اکسیر','Royal Time TV':'رویال تایم',
'Shabake 1':'شبکه یک','Shabake 2':'شبکه دو','Shabake 3':'شبکه سه','Shabake 4':'شبکه چهار','Shabake 5':'شبکه پنج','Shabake Khabar':'شبکه خبر','Shabake Khabar 2':'شبکه خبر ۲','Varzesh':'شبکه ورزش','Mostanad':'شبکه مستند','Nasim':'شبکه نسیم','Namayesh':'شبکه نمایش','Tamasha':'شبکه تماشا','Pooya':'شبکه پویا','Omid':'شبکه امید','Salamat':'شبکه سلامت','Amouzesh':'شبکه آموزش','iFilm Farsi':'آی‌فیلم فارسی','iFilm Dari':'آی‌فیلم دری','Ofogh':'شبکه افق','Quran':'شبکه قرآن',
'Abadan':'آبادان','Alborz':'البرز','Ardabil':'اردبیل','Birjand':'بیرجند','Bojnourd':'بجنورد','Booshehr':'بوشهر','Chahar Mahal':'چهارمحال و بختیاری','Esfahan':'اصفهان','Fars':'فارس','Gilan':'گیلان','Golestan':'گلستان','Hamedan':'همدان','Hormozgan':'هرمزگان','Ilam':'ایلام','Kerman':'کرمان','Kermanshah':'کرمانشاه','Khoozestan':'خوزستان','Kish':'کیش','Kordestan':'کردستان','Lorestan':'لرستان','Mahabad':'مهاباد','Markazi':'مرکزی','Mashhad':'خراسان رضوی','Mazandaran':'مازندران','Qazvin':'قزوین','Qom':'قم','Semnan':'سمنان','Sistan':'سیستان و بلوچستان','Tabriz':'تبریز','Urmia':'ارومیه','Yasouj':'یاسوج','Yazd':'یزد','Zanjan':'زنجان',
'Radio Hamrah':'رادیو همراه','Radio Yar':'رادیو یار','Radio Ran':'رادیو رن','Radio Setareh':'رادیو ستاره','Radio Shadi':'رادیو شادی','Radio Navahang':'رادیو نواهنگ','Radio Farda Rd':'رادیو فردا','Iran Intl Radio':'رادیو ایران اینترنشنال','Radio Parsa':'رادیو پارسا','Radio Mihan':'رادیو میهن','Radio Novin':'رادیو نوین','Radio Ava IR':'رادیو آوا'
};
const persianCategories = new Set(['فارسی','ایران','استانی','رادیو']);
export function displayName(name, category) {
 if (persianNames[name]) return persianNames[name];
 if (persianCategories.has(category)) {
  const words={TV:'تی‌وی',Radio:'رادیو',Iran:'ایران',Irani:'ایرانی',Persian:'فارسی',Persiana:'پرشیانا',Film:'فیلم',Series:'سریال',Music:'موزیک',Sport:'اسپرت',Sports:'اسپرت',Movies:'فیلم',News:'خبر',Family:'خانواده',Cinema:'سینما',Classic:'کلاسیک',World:'جهان',Live:'زنده',HD:'اچ‌دی',Farsi:'فارسی',English:'انگلیسی',Arabic:'عربی',Dari:'دری',International:'اینترنشنال',IRNA:'ایرنا',Press:'پرس',Alalam:'العالم',BBC:'بی‌بی‌سی',GEM:'جم',PMC:'پی‌ام‌سی',T2:'تی‌تو',Afra:'افرا',Grand:'گرند',Royal:'رویال',Time:'تایم',Navahang:'نواهنگ',Shabake:'شبکه',Shabakeh:'شبکه',Khabar:'خبر',Varzesh:'ورزش',Mostanad:'مستند',Nasim:'نسیم',Omid:'امید',Pooya:'پویا',Tamasha:'تماشا',Salamat:'سلامت',Ofogh:'افق',Quran:'قرآن',Amouzesh:'آموزش',Namayesh:'نمایش',Mihan:'میهن',Farda:'فردا',Ava:'آوا',Shadi:'شادی',Setareh:'ستاره',Hamrah:'همراه',Yar:'یار',Novin:'نوین',Ran:'رن'};
  return name.split(' ').map(x=>words[x]||x).join(' ');
 }
 return name;
}
// Channel identifiers are display labels; direct playback URLs are loaded from streams.json.
const seed = Object.entries(groups).flatMap(([category,s])=>s.split('|').map(name=>({id:name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''),name:displayName(name,category),originalName:name,category,type:'direct'})));
seed.unshift({id:'persiana-iranian',name:'پرشیانا ایرانی',originalName:'Persiana Iranian',category:'فارسی',type:'direct'});
export default [...new Map(seed.map(c=>[c.id,c])).values()];
